config/routes.rb
Outspoken::Application.routes.draw do
  resources :responses


  resources :dashboards


  resources :projects


  resources :videos


  # root :to => 'welcome#index'
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => redirect('/')
  match 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :speeches
  resources :users

  root :to => 'users#index'
end

app/models/video.rb
require 'open-uri'
require 'tempfile'

class Video < ActiveRecord::Base
  API_KEY = '25718772'
  API_SECRET = '5af4390c86057b8f1f561c0f751d595ebd800543'
  TOKEN = 'T1==cGFydG5lcl9pZD0yNTcxODc3MiZzZGtfdmVyc2lvbj10YnJ1YnktdGJyYi12MC45MS4yMDExLTAyLTE3JnNpZz01ZjFjMWEwZGY4OTM2NGNjNTM3Y2RiNjI5N2ExOGE1ODg2MGIwMjcxOnJvbGU9bW9kZXJhdG9yJnNlc3Npb25faWQ9Ml9NWDR5TlRjeE9EYzNNbjR4TWpjdU1DNHdMakYtVkhWbElFRndjaUF3T1NBeE1UbzBNRG93TkNCUVJGUWdNakF4TTM0d0xqTTNOamt3TXpSLSZjcmVhdGVfdGltZT0xMzY1NTMyODEwJm5vbmNlPTAuMTE5MTI5NzY3NDY5NDkyNDQmZXhwaXJlX3RpbWU9MTM2ODEyNDgxMiZjb25uZWN0aW9uX2RhdGE9'
  attr_accessible :tokbox_id, :tokbox_url, :user_id
  belongs_to :user

  after_create :upload_to_facebook

  def upload_to_facebook
    puts "user_id in model #{user_id}"
    puts "1 - #{tokbox_url}"
    while tokbox_url.blank? || tokbox_url =~ /itemNotFound/
      puts "2 - #{tokbox_url}"
      sleep 1
      self.tokbox_url = download_tokbox_url
    end
    puts "3 - #{tokbox_url}"

    tempfile = Tempfile.new(['foo', '.flv'])
    File.open(tempfile.path, 'wb') do |f|
      f.write(open(tokbox_url).read)
    end

    user = User.find(user_id)
    graph = Koala::Facebook::API.new(user.oauth_token)
    graph.put_video(tempfile.path)
    save!
  end

  def download_tokbox_url
    otsdk = OpenTok::OpenTokSDK.new(API_KEY, API_SECRET)
    otArchive = otsdk.getArchiveManifest(tokbox_id, TOKEN)
    otVideoResource = otArchive.resources[0]
    videoId = otVideoResource.getId()
    otArchive.downloadArchiveURL(videoId, TOKEN)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @video = Video.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
    puts "controller #{params.slice(:tokbox_id, :user_id)}"
    @video = Video.new(params.slice(:tokbox_id, :user_id))
    @video.save!
    head :ok

    # respond_to do |format|
    #   if @video.save
    #     format.html { redirect_to @video, notice: 'Video was successfully created.' }
    #     format.json { render json: @video, status: :created, location: @video }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @video.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :tokbox_id
    = f.text_field :tokbox_id
  .actions
    = f.submit 'Save'

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th Tokbox
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td= video.tokbox_id
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice

%p
  %b Tokbox:
  = @video.tokbox_id

= link_to 'Edit', edit_video_path(@video)
\|
= link_to 'Back', videos_path