config/routes.rb
Outspoken::Application.routes.draw do
  resources :responses


  resources :dashboards


  resources :projects


  resources :videos


  # root :to => 'welcome#index'
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => redirect('/')
  match 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :speeches
  resources :users

  root :to => 'users#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/functional_index.haml
.row-fluid.video
  .span12
    %iframe.centered{:allowfullscreen => "", :frameborder => "0", :height => "360", :src => "http://www.youtube.com/embed/hlVBg7_08n0", :width => "640"}

.row-fluid
  .span6
    .row-fluid
      .span12.well.sub-view.lyrics
        %h6 Macklemore and Ryan Lewis Ft.Mary Lambert - “Same Love”
        %p
          When I was in the third grade I thought that I was gay
          'Cause I could draw, my uncle was, and I kept my room straight
          I told my mom tears rushing down my face
          She's like "Ben you've loved girls since before pre-k tripping,"
          Yeah, I guess she had a point, didn't she?
          Bunch of stereotypes all in my head.
          I remember doing the math like, "Yeah, I'm good at little league"
          A preconceived idea of what it all meant
          For those that liked the same sex
          Had the characteristics
          The right wing conservatives think it's a decision
          And you can be cured with some treatment and religion
          Man-made rewiring of a predisposition
          Playing God, aw nah here we go
          America the brave still fears what we don't know
          And God loves all his children, is somehow forgotten
          But we paraphrase a book written thirty-five-hundred years ago
          I don't know
        %p
          And I can't change
          Even if I tried
          Even if I wanted to
          I can't change
          Even if I try
          Even if I wanted to
          My love
          My love
          My love
          She keeps me warm
          She keeps me warm
          She keeps me warm
          She keeps me warm
        %p
          If I was gay, I would think hip-hop hates me
          Have you read the YouTube comments lately?
          "Man, that's gay" gets dropped on the daily
          We become so numb to what we're saying
          A culture founded from oppression
          Yet we don't have acceptance for 'em
          Call each other faggots behind the keys of a message board
          A word rooted in hate, yet our genre still ignores it
          Gay is synonymous with the lesser
          It's the same hate that's caused wars from religion
          Gender to skin color, the complexion of your pigment
          The same fight that led people to walk outs and sit ins
          It's human rights for everybody, there is no difference!
          Live on and be yourself
          When I was at church they taught me something else
          If you preach hate at the service those words aren't anointed
          That holy water that you soak in has been poisoned
          When everyone else is more comfortable remaining voiceless
          Rather than fighting for humans that have had their rights stolen
          I might not be the same, but that's not important
          No freedom till we're equal, damn right I support it
        %p (I don't know)
        %p
          And I can't change
          Even if I tried
          Even if I wanted to
          My love
          My love
          My love
          She keeps me warm
          She keeps me warm
          She keeps me warm
          She keeps me warm
        %p
          We press play, don't press pause
          Progress, march on
          With the veil over our eyes
          We turn our back on the cause
          Till the day that my uncles can be united by law
          When kids are walking 'round the hallway plagued by pain in their heart
          A world so hateful some would rather die than be who they are
          And a certificate on paper isn't gonna solve it all
          But it's a damn good place to start
          No law is gonna change us
          We have to change us
          Whatever God you believe in
          We come from the same one
          Strip away the fear
          Underneath it's all the same love
          About time that we raised up
        %p
          And I can't change
          Even if I tried
          Even if I wanted to
          I can't change
          Even if I try
          Even if I wanted to
          My love
          My love
          My love
          She keeps me warm
          She keeps me warm
          She keeps me warm
          She keeps me warm
          Love is patient
          Love is kind
          Love is patient
          Love is kind
          (I'm not crying on Sundays)
          Love is patient
          (I'm not crying on Sundays)
          Love is kind
          (I'm not crying on Sundays)
          Love is patient
          (I'm not crying on Sundays)
          Love is kind
          (I'm not crying on Sundays)
          Love is patient
          (I'm not crying on Sundays)
          Love is kind
          (I'm not crying on Sundays)
          Love is patient
          Love is kind

  .span6
    .row-fluid.question-list
      .span12.well.sub-view
        %h6 Questions
        %ul.unstyled
          %li.question.mc-question
            1. Which of these statements BEST summarizes Macklemore’s use of rhetoric devices throughout the song:
            %small ( CCSS.ELA-Literacy.SL.9-10.1c)
          %li.question.fr-question
            2. Evaluate Macklemore’s argument in favor of equal rights. Use specific lyrics or examples from the song to support your argument.
            %small (CCSS.ELA-Literacy.SL.9-10.3)
          %li.question.vid-question
            3.  Inspired?  Write a poem response, journal entry,  persuasive speech, or any kind of writing that captures your passion and opinions!  Post your writing or upload your video to keep the conversation going!
            %small (CCSS.ELA-Literacy.SL.9-10.1d, CCSS.ELA-Literacy.WHST.9-10.6)

    .row-fluid.multiple-choice
      .span12.well.sub-view
        %h6 Please answer the following question:
        %form
          %label.radio
            %input#optionsRadios1{:checked => "", :name => "optionsRadios", :type => "radio", :value => "option1"}/
            Option one is this and that—be sure to include why it's great
          %label.radio
            %input#optionsRadios2{:name => "optionsRadios", :type => "radio", :value => "option2"}>/
            Option two can be something else and selecting it will deselect the others
          %label.radio
            %input#optionsRadios2{:name => "optionsRadios", :type => "radio", :value => "option2"}>/
            Option three can be something else and selecting it will deselect the others
        %button.btn.pull-right.mc-back{:type => "button"} Submit
        %button.btn.pull-right.mc-back{:type => "button"} Back


    .row-fluid.free-response
      .span12.well
        %h6 Please answer the following question:
        %form
          %textarea.input-block-level{:rows => "12"}
        %button.btn.pull-right.fr-back{:type => "button"} Submit
        %button.btn.pull-right.fr-back{:type => "button"} Back

    .row-fluid.video-response
      .span12.well.sub-view
        %h6 Please answer the following question:
        %div Video Object will go here
        %button.btn.pull-right.vid-back{:type => "button"} Back

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path