config/routes.rb
Outspoken::Application.routes.draw do
  resources :responses


  resources :dashboards


  resources :projects


  resources :videos


  # root :to => 'welcome#index'
  match 'auth/:provider/callback', :to => 'sessions#create'
  match 'auth/failure', :to => redirect('/')
  match 'signout', :to => 'sessions#destroy', :as => 'signout'

  resources :speeches
  resources :users

  root :to => 'users#index'
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  # GET /dashboards
  # GET /dashboards.json
  def index
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.json
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render json: @dashboard, status: :created, location: @dashboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.json
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to dashboards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.haml
= form_for @dashboard do |f|
  - if @dashboard.errors.any?
    #error_explanation
      %h2= "#{pluralize(@dashboard.errors.count, "error")} prohibited this dashboard from being saved:"
      %ul
        - @dashboard.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/dashboards/edit.html.haml
%h1 Editing dashboard

= render 'form'

= link_to 'Show', @dashboard
\|
= link_to 'Back', dashboards_path

app/views/dashboards/new.html.haml
%h1 New dashboard

= render 'form'

= link_to 'Back', dashboards_path

app/views/dashboards/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_dashboard_path(@dashboard)
\|
= link_to 'Back', dashboards_path